# Generated by Django 5.0 on 2023-12-08 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackType',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('port', models.PositiveIntegerField(null=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detect_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
