# Generated by Django 5.0 on 2023-12-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owaspapp', '0002_rename_event_id_attacktype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacktype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
